server.port: 9000
management:
  server.port: 9001
  endpoints.web.exposure.include: info,health

logging:
  level:
    root: WARN
    com.asurint: DEBUG

info:
  app: directory-service
  version: 1.0